num1 = int(input ("Please enter num1: "))
num2 = int(input ("Please enter num2: "))
print (num1&num2)
print (num1|num2)
print (num1^num2)
print (num1>>num2)
print (num1<<num2)
print (num1+num2)
print (num1-num2)
print (num1*num2)
print (num1/num2)
print (num1>num2)
print (num1<num2)
print (num1==num2)